export const ROLE_OPTIONS = [
  { label: "Owner", value: "owner" },
  { label: "Non Owner", value: "non_owner" },
];

export const SAMPLE_DATA = [
  {
    email: "oliver@example.com",
    current_sign_in_at: null,
    last_name: "Singh",
    first_name: "Neeraj",
    id: "a385f9d2-e2c9-45ce-abfc-aef711a5a926",
    profile_image_url:
      "https://www.neetoauth.net/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaEpJaWsxTW1NeVlUSTJZaTAxT0RJd0xUUmpOVFV0WWprMU9TMDVaREEzWkdZd1l6TmhZbVVHT2daRlZBPT0iLCJleHAiOm51bGwsInB1ciI6ImJsb2JfaWQifX0=--2f99eaa63fbc27c97687b71b35d313bb7c6a5cc7/download.png",
    role: "owner",
    invite_status: "not_invited",
    active: true,
  },
  {
    email: "ghouse.mohamed@bigbinary.com",
    current_sign_in_at: null,
    last_name: "Mohamed",
    first_name: "Ghouse",
    id: "7c2845f2-d8e6-450b-99f5-9243c2cf1d90",
    profile_image_url: null,
    role: "non_owner",
    invite_status: "not_invited",
    active: true,
  },
  {
    email: "julie@bigbinary.com",
    current_sign_in_at: null,
    last_name: "Agent",
    first_name: "Julie",
    id: "10b8fe97-8970-4032-855b-fd325c204874",
    profile_image_url: null,
    role: "non_owner",
    invite_status: "not_invited",
    active: true,
  },
  {
    email: "edwin.babu@bigbinary.com",
    current_sign_in_at: null,
    last_name: "Bigbinary",
    first_name: "Edwin",
    id: "551a0b69-c405-47c6-8e91-71b3cb98b09d",
    profile_image_url: null,
    role: "non_owner",
    invite_status: "not_invited",
    active: true,
  },
  {
    email: "meghana@gmail.com",
    current_sign_in_at: null,
    last_name: "S",
    first_name: "Meghana",
    id: "a56eeb8a-0a8a-4eaf-85f6-414c21b5fe2d",
    profile_image_url: null,
    role: "non_owner",
    invite_status: "not_invited",
    active: true,
  },
  {
    email: "meghanagowda2013@gmail.com",
    current_sign_in_at: null,
    last_name: "s",
    first_name: "meghna",
    id: "99a17e2b-7cea-478a-9a3a-f3f7edfc6655",
    profile_image_url: null,
    role: "non_owner",
    invite_status: "not_invited",
    active: true,
  },
  {
    email: "meghana.s+deliver@bigbinary.com",
    current_sign_in_at: null,
    last_name: "Shankar",
    first_name: "Meghana",
    id: "b8d7a50d-f615-4486-b04b-574962e19f6e",
    profile_image_url: null,
    role: "non_owner",
    invite_status: "not_invited",
    active: true,
  },
  {
    email: "meghanashivashankar2013@gmail.com",
    current_sign_in_at: null,
    last_name: "Shankar",
    first_name: "Meghna",
    id: "640737a9-32a2-4089-920e-d3dba5012308",
    profile_image_url: null,
    role: "non_owner",
    invite_status: "not_invited",
    active: true,
  },
  {
    email: "meghana.s@gmail.com",
    current_sign_in_at: null,
    last_name: "12",
    first_name: "123",
    id: "21980720-68e9-4433-b3e1-a042d0f4aaa1",
    profile_image_url: null,
    role: "non_owner",
    invite_status: "not_invited",
    active: true,
  },
  {
    email: "meghana.p@gmail.com",
    current_sign_in_at: null,
    last_name: "P",
    first_name: "Meghana",
    id: "2f40da98-3809-4883-87e7-5265e9aba511",
    profile_image_url: null,
    role: "non_owner",
    invite_status: "not_invited",
    active: true,
  },
  {
    email: "meghana.s@bigbinary.com",
    current_sign_in_at: null,
    last_name: "Choudhary",
    first_name: "Julie",
    id: "05c3e69e-ba33-4338-b379-6e7b4d0a33fc",
    profile_image_url: null,
    role: "non_owner",
    invite_status: "not_invited",
    active: true,
  },
  {
    email: "ghouse.mohamed+testagent@bigbinary.com",
    current_sign_in_at: null,
    last_name: "Agent",
    first_name: "Test",
    id: "faf3173b-9f7d-4d21-8e80-107e5c4b4152",
    profile_image_url: null,
    role: "non_owner",
    invite_status: "not_invited",
    active: true,
  },
  {
    email: "jhon@gmail.com",
    current_sign_in_at: null,
    last_name: "S",
    first_name: "John",
    id: "7da29cca-1cc8-4b4a-95a7-bd52301e23b6",
    profile_image_url: null,
    role: "non_owner",
    invite_status: "not_invited",
    active: true,
  },
  {
    email: "haseebeqx@gmail.com",
    current_sign_in_at: null,
    last_name: "A",
    first_name: "Haseeb",
    id: "2b5745c8-31eb-4ea7-b84e-ded8022e8f1a",
    profile_image_url: null,
    role: "non_owner",
    invite_status: "not_invited",
    active: true,
  },
  {
    email: "haseeb.a@bigbinary.com",
    current_sign_in_at: null,
    last_name: "Annadamban",
    first_name: "Haseeb",
    id: "0e8c1a96-37e2-4720-95eb-b0b7f991dd70",
    profile_image_url: null,
    role: "non_owner",
    invite_status: "not_invited",
    active: true,
  },
  {
    email: "abraham@gmail.com",
    current_sign_in_at: null,
    last_name: "Abraham",
    first_name: "John",
    id: "617e8532-eef7-49d5-b4d1-e4e8968ef678",
    profile_image_url: null,
    role: "non_owner",
    invite_status: "not_invited",
    active: true,
  },
  {
    email: "123456@gmail.com",
    current_sign_in_at: null,
    last_name: "123456",
    first_name: "123456",
    id: "41f0943b-7faa-4a97-a9a7-d825462dab44",
    profile_image_url: null,
    role: "non_owner",
    invite_status: "not_invited",
    active: true,
  },
  {
    email: "sapnagwda@gmai.com",
    current_sign_in_at: null,
    last_name: "k",
    first_name: "sap",
    id: "37b05dcc-f18e-4216-963b-3797cefd63f5",
    profile_image_url: null,
    role: "non_owner",
    invite_status: "not_invited",
    active: true,
  },
  {
    email: "sandip.mane@bigbinary.com",
    current_sign_in_at: null,
    last_name: "Mane",
    first_name: "Sandip",
    id: "9dfad584-2e16-4774-bd00-f99b0ba7b36c",
    profile_image_url: null,
    role: "non_owner",
    invite_status: "not_invited",
    active: true,
  },
  {
    email: "rishav.kumar@bigbinary.com",
    current_sign_in_at: null,
    last_name: "-",
    first_name: "rishav.kumar",
    id: "3338c3f2-db14-413a-93a7-04e50fe8b078",
    profile_image_url: null,
    role: "non_owner",
    invite_status: "not_invited",
    active: true,
  },
];
